apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-credential-helper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cupperservice/kappaas-apps.git
    path: charts/aws-credential-helper
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-credential-helper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
