apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - aws-credential-helper.yaml
  - external-secrets.yaml
  - cloudflare-tunnel.yaml
  - metrics-server.yaml
