apiVersion: v1
kind: Service
metadata:
  name: aws-credential-helper
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aws-credential-helper
  ports:
    - port: 9911
      targetPort: 9911
      protocol: TCP
  type: ClusterIP
