apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-kakeibon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kakeibon
  project: default
  sources:
    - path: components
      repoURL: https://github.com/cupperservice/kakeibon-apps.git
      targetRevision: deploy-with-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  