apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kakeibon-secret-store
  namespace: kakeibon
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kakeibon-apps-secret
  namespace: kakeibon
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: kakeibon-secret-store
    kind: SecretStore
  target:
    name: kakeibon-apps-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: "https://github.com/cupperservice/kakeibon-apps.git"
        name: "kakeibon-apps"
        username: "cupperservice"
        password: "{{ .githubpat }}"
  data:
    - secretKey: githubpat
      remoteRef:
        key: kappaas-apps/repositories/kakeibon-apps/github-personal-access-token
