aws:
  region: ap-northeast-1
  trustAnchorArn: ""
  profileArn: ""
  roleArn: ""

certificate:
  commonName: k8s-workload
  duration: 720h
  renewBefore: 72h
  issuerRef:
    name: k8s-ca
    kind: ClusterIssuer
