apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    ingress:
      {{- range .Values.ingress }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
      {{- end }}
      - service: http_status:404
