apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cloudflare-tunnel-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-tunnel-secret-store
    kind: SecretStore
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: kappaas-apps/cloudflare/token
